---
title: "Geographic Visualization of Gun Violence in the U.S."
author: "Bich Ngoc Nguyen, Felix Ung, Anna Voloshina, Delaney Wu"
date: "1/12/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ACCESSING THE /source DIRECTORY
```{r, message=F, warning=F}
source("../source/table.R")
source("../source/chart_1.R")
```

## Summary


## Table
### Table | Total Deaths in State
```{r table, echo=FALSE, message=F, warning=F}
library(knitr)
library(kableExtra)
kable(state, format = "html") %>%
  kable_styling("striped", full_width = F, position = "float_left") %>% 
 scroll_box(width = "300px", height = "300px")
```

### Table | Total Deaths in City
```{r table2, echo=FALSE, message=F, warning=F}
kable(city, format = "html") %>%
  kable_styling("striped", full_width = F, position = "left") %>% 
 scroll_box(width = "300px", height = "300px")
```

### Table | Total Deaths of Date
```{r table3, echo=FALSE, message=F, warning=F}
kable(date, format = "html") %>%
  kable_styling("striped", full_width = F, position = "left") %>% 
 scroll_box(width = "300px", height = "300px")
```



## Charts
### Visualization of Total Gun Violence Incidence (2013-2018)

```{r chart_1, echo=FALSE}
plot(state_bar_chart)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
